apiVersion: v1 
kind: Pod 
metadata: 
   name: myresourcespod
   labels:
     app: myblue-pod
spec: 
  containers: 
    - name: myblue-container
      image: nginx
      ports:
        - containerPort: 80
  resources:
    requests:
      cpu: 250m
      memory: 64Mi  
    limits:
      cpu: 500m
      memory: 128Mi
                   
       