apiVersion: v1 
kind: Pod 
metadata:
  name: mysecret-pod
spec: 
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: secret-pod
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: secret-pod         
